# Generated by Django 4.2.4 on 2023-08-26 06:22

import director.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=50, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('web_address', models.CharField(max_length=100, validators=[director.models.validate_url])),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_time', models.DateTimeField()),
                ('image_url', models.CharField(max_length=1000, validators=[director.models.validate_url])),
                ('is_correctly_identified', models.BooleanField()),
                ('slug', models.SlugField(blank=True, null=True)),
                ('camera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.cameramodel')),
                ('offline_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
