# Generated by Django 4.2.4 on 2023-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_detectyoutubemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectyoutubemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
