# Generated by Django 4.2.4 on 2023-08-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0003_alter_detectyoutubemodel_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetectYouTubeModel',
        ),
    ]
